# -*- coding: utf-8 -*-
"""RECURSION

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g2VK-tFElwuMPBIA8AI8HeYzrZs5scr_
"""

def fibonacci (n):
  if n<=0:
    print("incorrect input")
  elif n==1:
    return 0
  elif n==2:
    return 1
  else:
    return fibonacci(n-1)+fibonacci(n-2)
print(fibonacci(5))

def fibonacci(n):
  if n<=1:
    return n
  else:
    return (fibonacci(n-1)+fibonacci(n-2))
n_terms=int(input("enter your valid number"))
if n_terms<=0:
  print("invalid input")
else:
  print("fibonaccci series")
for i in range (n_terms):
  print(fibonacci(i))